#!/usr/bin/env bash

systemctl restart haproxy || exit 1
cat rsa.pem || exit 1
python3 -m venv venv || exit 1
source venv/bin/activate || exit 1
pip install -r requirements.txt || exit 1

python3 signing_server.py
