#!/usr/bin/env bash

echo "$(date +%Y%m%d%H%M%S) -> -> -> Starting new runtime of an RSA signing service."

git clone https://github.com/jpegleg/signer-daemon && mv signer-daemon/* .

pip install --upgrade pip
haproxy -f /etc/haproxy/haproxy.cfg & || exit 1
cat rsa.pem || exit 1
python3 -m venv venv || exit 1
source venv/bin/activate || exit 1
pip install -r requirements.txt || exit 1

python3 signing_server.py || echo "$(date +%Y%m%d%H%M%S) <- <- <- service runtime down."
