#!/usr/bin/env bash

TID="$(openssl rand -hex 16 | cut -c 1-15)"

listener () {
  nc -l localhost "$1" || echo "$(date +%Y%m%d%H%M%S) - Listener drop, restarting..."
}

request () {
  tmpid=tmpId__$(openssl rand -hex 16)
  echo "$1" > "$tmpid"
  time openssl rsautl -sign -in "$tmpid" -inkey rsa.key -out output.sign_$TID
}

daemonize () {
  while true; do
    echo "$(date +%Y%m%d%H%M%S%N) - New proc init."
    returned="$(listener 50042)" && request "$returned" || echo "$(date +%Y%m%d%H%M%S) - Listener drop, restarting..."
    echo "$(date +%Y%m%d%H%M%S%N) - Closing data in from receive netcat exit."
    echo -n "$(cat ./output.sign | base64)" | redis-cli -x set latestSigner
    XIID="$(echo $(openssl rand -hex 32)-$(date +%Y%m%d%H%M%S%N))"
    echo -n "$(cat ./output.sign | base64)" | redis-cli -x set "$XIID"
    redis-cli expire "$XIID" 120 && echo "$(date +%Y%m%d%H%M%S%N) - proc XIID set in redis: $XIID."
  done
}

main () {
  daemonize 2>&1 > shellery2_rsa.log
}

find . -name "tmpId__" -mtime +1 -exec gzip -9 {} \; &
find . -name "tmpId__*.gz" -mtime +30 -exec rm -f {} \; &
find . -name "output.sign_*" -mtime +3 -exec rm -f {} \; &

main || exit 1
